version: '3'
services:
  mysql-m:
    image: mysql:8.0
    container_name: mysql-m
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-m-data:/var/lib/mysql
      - ./master-init.sql:/docker-entrypoint-initdb.d/master-init.sql
      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - mysql-cluster

  mysql-s1:
    image: mysql:8.0
    container_name: mysql-s1
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
    ports:
      - "3307:3306"
    volumes:
      - mysql-s1-data:/var/lib/mysql
#      - ./slave-init.sql:/docker-entrypoint-initdb.d/slave-init.sql
      - ./config/my-slave.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - mysql-cluster
    depends_on:
      - mysql-m
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 5

  mysql-s2:
    image: mysql:8.0
    container_name: mysql-s2
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: test_db
    ports:
      - "3308:3306"
    volumes:
      - mysql-s2-data:/var/lib/mysql
#      - ./slave-init.sql:/docker-entrypoint-initdb.d/slave-init.sql
      - ./config/my-slave.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - mysql-cluster
    depends_on:
      - mysql-m
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 5

volumes:
  mysql-m-data: {}
  mysql-s1-data: {}
  mysql-s2-data: {}

networks:
  mysql-cluster:
    driver: bridge
